- hosts: minecraft
  become: yes
  tasks:
    - name: Update the system
      shell: yum update -y
    - name: Install Java
      shell: yum install -y java-17-amazon-corretto-headless
    - name: Create Minecraft directory
      file:
        path: /home/ec2-user/minecraft
        state: directory
        owner: ec2-user
        group: ec2-user
    - name: Download Minecraft server
      get_url:
        url: https://piston-data.mojang.com/v1/objects/84194a2f286ef7c14ed7ce0090dba59902951553/server.jar
        dest: /home/ec2-user/minecraft/server.jar
    - name: Accept EULA
      copy:
        content: "eula=true\n"
        dest: /home/ec2-user/minecraft/eula.txt
    - name: Create Systemd service file
      copy:
        content: |
          [Unit]
          Description=Minecraft Server
          Wants=network-online.target
          [Service]
          User=ec2-user
          WorkingDirectory=/home/ec2-user/minecraft
          ExecStart=/usr/bin/java -Xmx1300M -Xms1300M -jar server.jar nogui
          Restart=on-failure
          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/minecraft.service
    - name: Reload systemd and enable Minecraft service
      systemd:
        daemon_reload: yes
        name: minecraft
        enabled: yes
        state: started
